name: Deploy MultiDocker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t linhnvhdev/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true linhnvhdev/react-test npm test --coverage
 
      - run: docker build -t linhnvhdev/multi-client-udemy ./client
      - run: docker build -t linhnvhdev/multi-nginx-udemy ./nginx
      - run: docker build -t linhnvhdev/multi-server-udemy ./server
      - run: docker build -t linhnvhdev/multi-worker-udemy ./worker
 
      - run: docker push linhnvhdev/multi-client-udemy
      - run: docker push linhnvhdev/multi-nginx-udemy
      - run: docker push linhnvhdev/multi-server-udemy
      - run: docker push linhnvhdev/multi-worker-udemy
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-multiple-udemy
          environment_name: Dockermultipleudemy-env
          existing_bucket_name: elasticbeanstalk-us-east-1-482782894675
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip